# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hungry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FMDB'
  pod 'Alamofire'
  pod 'SwiftLocation'
  pod 'Kingfisher'
  pod 'AsyncSwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'RKParallaxEffect'

  target 'HungryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HungryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
